---
- hosts: webserver
  become: yes
  gather_facts: true
  vars:
    home_dir: /home/ubuntu/home
  vars_files:
    - vars/variables
  environment:
    FLASK_APP: "{{ home_dir }}/app.py"  
  tasks:
    - include_tasks: tasks/setup.yml
    - include_tasks: tasks/setup_code_base.yml
    # - include_tasks: tasks/setup_node.yml
    #- include_tasks: tasks/setup_node_files.yml
